-- MySQL Script generated by MySQL Workbench
-- lun 09 nov 2020 21:15:31 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DondeEstanAppDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DondeEstanAppDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DondeEstanAppDB` ;
USE `DondeEstanAppDB` ;

-- -----------------------------------------------------
-- Table `DondeEstanAppDB`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DondeEstanAppDB`.`USERS` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `numberId` LONGBLOB NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DondeEstanAppDB`.`USERS_OBSERVEES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DondeEstanAppDB`.`USERS_OBSERVEES` (
  `privacyKey` VARCHAR(45) NOT NULL,
  `companyName` VARCHAR(45) NOT NULL,
  `licensePlate` VARCHAR(45) NOT NULL,
  `carRegistration` VARCHAR(45) NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`userId`),
  INDEX `fk_USERS_OBSERVEES_USERS_idx` (`userId` ASC) VISIBLE,
  UNIQUE INDEX `privacyKey_UNIQUE` (`privacyKey` ASC) VISIBLE,
  CONSTRAINT `fk_USERS_OBSERVEES_USERS`
    FOREIGN KEY (`userId`)
    REFERENCES `DondeEstanAppDB`.`USERS` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DondeEstanAppDB`.`USERS_OBSERVEES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DondeEstanAppDB`.`USERS_OBSERVEES` (
  `privacyKey` VARCHAR(45) NOT NULL,
  `companyName` VARCHAR(45) NOT NULL,
  `licensePlate` VARCHAR(45) NOT NULL,
  `carRegistration` VARCHAR(45) NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`userId`),
  INDEX `fk_USERS_OBSERVEES_USERS_idx` (`userId` ASC) VISIBLE,
  UNIQUE INDEX `privacyKey_UNIQUE` (`privacyKey` ASC) VISIBLE,
  CONSTRAINT `fk_USERS_OBSERVEES_USERS`
    FOREIGN KEY (`userId`)
    REFERENCES `DondeEstanAppDB`.`USERS` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DondeEstanAppDB`.`OBSERVERS_USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DondeEstanAppDB`.`OBSERVERS_USERS` (
  `childsName` INT NOT NULL,
  `userId` INT NOT NULL,
  `userObserveeIdFK` INT NOT NULL,
  PRIMARY KEY (`userId`),
  INDEX `fk_OBSERVERS_USERS_USERS_OBSERVEES1_idx` (`userObserveeIdFK` ASC) VISIBLE,
  CONSTRAINT `fk_OBSERVERS_USERS_USERS1`
    FOREIGN KEY (`userId`)
    REFERENCES `DondeEstanAppDB`.`USERS` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OBSERVERS_USERS_USERS_OBSERVEES1`
    FOREIGN KEY (`userObserveeIdFK`)
    REFERENCES `DondeEstanAppDB`.`USERS_OBSERVEES` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DondeEstanAppDB`.`NOTIFICATIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DondeEstanAppDB`.`NOTIFICATIONS` (
  `notificationId` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `userObserveeIdFK` INT NOT NULL,
  PRIMARY KEY (`notificationId`),
  INDEX `fk_NOTIFICATIONS_USERS_OBSERVEES1_idx` (`userObserveeIdFK` ASC) VISIBLE,
  CONSTRAINT `fk_NOTIFICATIONS_USERS_OBSERVEES1`
    FOREIGN KEY (`userObserveeIdFK`)
    REFERENCES `DondeEstanAppDB`.`USERS_OBSERVEES` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DondeEstanAppDB`.`MESSAGES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DondeEstanAppDB`.`MESSAGES` (
  `messageId` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `observerUserIdFK` INT NOT NULL,
  `userObserveeIdFK` INT NOT NULL,
  PRIMARY KEY (`messageId`),
  INDEX `fk_MESSAGES_OBSERVERS_USERS1_idx` (`observerUserIdFK` ASC) VISIBLE,
  INDEX `fk_MESSAGES_USERS_OBSERVEES1_idx` (`userObserveeIdFK` ASC) VISIBLE,
  CONSTRAINT `fk_MESSAGES_OBSERVERS_USERS1`
    FOREIGN KEY (`observerUserIdFK`)
    REFERENCES `DondeEstanAppDB`.`OBSERVERS_USERS` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MESSAGES_USERS_OBSERVEES1`
    FOREIGN KEY (`userObserveeIdFK`)
    REFERENCES `DondeEstanAppDB`.`USERS_OBSERVEES` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DondeEstanAppDB`.`ADDRESSES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DondeEstanAppDB`.`ADDRESSES` (
  `addressId` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `floor` VARCHAR(5) NULL,
  `apartament` VARCHAR(45) NULL,
  `zipCode` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `latitude` VARCHAR(45) NOT NULL,
  `longitude` VARCHAR(45) NOT NULL,
  `observerUserIdFK` INT NOT NULL,
  PRIMARY KEY (`addressId`),
  INDEX `fk_ADDRESSES_OBSERVERS_USERS1_idx` (`observerUserIdFK` ASC) VISIBLE,
  CONSTRAINT `fk_ADDRESSES_OBSERVERS_USERS1`
    FOREIGN KEY (`observerUserIdFK`)
    REFERENCES `DondeEstanAppDB`.`OBSERVERS_USERS` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DondeEstanAppDB`.`LOCATIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DondeEstanAppDB`.`LOCATIONS` (
  `locationId` INT NOT NULL AUTO_INCREMENT,
  `dayHour` VARCHAR(45) NOT NULL,
  `latitude` VARCHAR(45) NOT NULL,
  `longitude` VARCHAR(45) NOT NULL,
  `userObserveeIdFK` INT NOT NULL,
  PRIMARY KEY (`locationId`),
  INDEX `fk_LOCATIONS_USERS_OBSERVEES1_idx` (`userObserveeIdFK` ASC) VISIBLE,
  CONSTRAINT `fk_LOCATIONS_USERS_OBSERVEES1`
    FOREIGN KEY (`userObserveeIdFK`)
    REFERENCES `DondeEstanAppDB`.`USERS_OBSERVEES` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DondeEstanAppDB`.`ARRIVALS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DondeEstanAppDB`.`ARRIVALS` (
  `arrivalId` INT NOT NULL AUTO_INCREMENT,
  `dayHour` VARCHAR(45) NOT NULL,
  `userObserveeIdFK` INT NOT NULL,
  `observerUserIdFK` INT NOT NULL,
  `addressIdFK` INT NOT NULL,
  `locationIdFK` INT NOT NULL,
  PRIMARY KEY (`arrivalId`),
  INDEX `fk_ARRIVALS_USERS_OBSERVEES1_idx` (`userObserveeIdFK` ASC) VISIBLE,
  INDEX `fk_ARRIVALS_OBSERVERS_USERS1_idx` (`observerUserIdFK` ASC) VISIBLE,
  INDEX `fk_ARRIVALS_ADDRESSES1_idx` (`addressIdFK` ASC) VISIBLE,
  INDEX `fk_ARRIVALS_LOCATIONS1_idx` (`locationIdFK` ASC) VISIBLE,
  CONSTRAINT `fk_ARRIVALS_USERS_OBSERVEES1`
    FOREIGN KEY (`userObserveeIdFK`)
    REFERENCES `DondeEstanAppDB`.`USERS_OBSERVEES` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ARRIVALS_OBSERVERS_USERS1`
    FOREIGN KEY (`observerUserIdFK`)
    REFERENCES `DondeEstanAppDB`.`OBSERVERS_USERS` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ARRIVALS_ADDRESSES1`
    FOREIGN KEY (`addressIdFK`)
    REFERENCES `DondeEstanAppDB`.`ADDRESSES` (`addressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ARRIVALS_LOCATIONS1`
    FOREIGN KEY (`locationIdFK`)
    REFERENCES `DondeEstanAppDB`.`LOCATIONS` (`locationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
